site_name: OnBoardTips
site_url: https://lisr-pcx.github.io/on-board-tips

nav:
  - Welcome: index.md
  - 'Focus on C/C++':
    - Basics: basics_c_cpp.md
    - Pointers
    - Constants: constants.md
    - Memory management
    - Data structures
    - STL
    - Lamba Expressions
    - Threads
    - Sockets
  - 'General':
    - Technical documentation: technical_documentation.md
    - Git basics: git_basics.md
    - Regular Expressions: regular_expressions.md
    - Wireshark and tcpdump: wireshark_tcpdump.md
    - Embedded Systems: embedded.md
    - Defensive programming: defensive_programming.md
  - 'Operative Systems':
    - Work with Linux: linux_os.md
    - Fedora OS: linux_fedora.md
  - 'Workflow':
    - Analysis and Design: analysis_and_design.md
    - Debugging: debugging.md
    - Code reviews: code_reviews.md
    - Test Driven Development: tdd_workflow.md
  - 'Extra':
    - Tips for Junior Devs: tips_for_junior_devs.md
    - Tips for Team Leaders: tips_for_team_leaders.md
    - More stuff: more_stuff.md
    - Podcast and books: podcast_books.md
    - About: about.md

theme: 
  name: readthedocs
  include_homepage_in_sidebar: False
  prev_next_buttons_location: none
  titles_only: True
  logo: null
  custom_dir: custom_theme/

markdown_extensions:
  - admonition

extra_css:
  - style.css
