site_name: OnBoardTips
site_url: https://lisr-pcx.github.io/on-board-tips

nav:
  - Welcome: index.md
  - 'C++ language':
    - Overview: cpp_overview.md
    - 'Focus on':
      - constants: cpp_constants.md
    - Conferences and keynotes: cpp_conferences.md
  - 'ADA language':
    - Overview: ada_overview.md
  - 'General':
    - Technical documentation: technical_documentation.md
    - Git basics: git_basics.md
    - Regular Expressions: regular_expressions.md
    - Wireshark and tcpdump: wireshark_tcpdump.md
    - Embedded Systems: embedded.md
    - Defensive programming: defensive_programming.md
  - 'Operative Systems':
    - Work with Linux: linux_os.md
    - Fedora Linux: linux_fedora.md
  - 'Workflow':
    - SDLC models: sdlc_models.md
    - Test Driven Development: tdd_workflow.md
    - Debugging: debugging.md
    - Code reviews: code_reviews.md
  - 'Extra':
    - Tips for Junior Devs: tips_for_junior_devs.md
    - Tips for Team Leaders: tips_for_team_leaders.md
    - More stuff: more_stuff.md
    - Podcasts and books: podcasts_books.md
    - About: about.md

theme: 
  name: readthedocs
  include_homepage_in_sidebar: False
  prev_next_buttons_location: none
  titles_only: True
  logo: null
  custom_dir: custom_theme/

markdown_extensions:
  - admonition

extra_css:
  - style.css
